### ISSUE TITLE
Can not be build on i586

### ISSUE THREAD

**Issue by asy972** [lkinley/Crypt-OpenSSH-ChachaPoly#1]
I attempted to build the module on i586 system and it fail:

`PERL_DL_NONLAZY=1 "/usr/bin/perl5.22.1" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef  *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t`
`t/Crypt-OpenSSH-ChachaPoly.t .. 1/3 Invalid type 'Q' in pack at t/Crypt-OpenSSH-ChachaPoly.t line 25.`
`# Looks like you planned 3 tests but ran 1.`
`# Looks like your test exited with 255 just after 1.`
`t/Crypt-OpenSSH-ChachaPoly.t .. Dubious, test returned 255 (wstat 65280, 0xff00)`
`Failed 2/3 subtests`

And the module was built on x86_64 successful

UPD: sorry, it is problem of perl possible; I will clarify later.

**Comment by lkinley** [comment]
Pull latest and try again.

**Comment by asy972** [comment]
Thanks. It works.
